### ISSUE TITLE
Location of the org-roam.db

### ISSUE THREAD

**Issue by rnwolf** [AloisJanicek/org-roam-server-light#1]
Hi Thanks for your work. I was trying to get it working on my DOOM emacs install, on my Windows 10, laptop.

There is a problem with the location of the org-roam.db
It is located at  ```C:\Users\rnwol\.emacs.d\.local\etc\org-roam.db``
and my roam notes are in ```C:\Users\rnwol\org\roam```

It seems that the location of the database was recently changed.  
See https://github.com/org-roam/org-roam/pull/1164

**Comment by AloisJanicek** [comment]
Thanks for bringing this to my attention, I think I fixed it in https://github.com/AloisJanicek/org-roam-server-light/commit/fde0b4b4e8f5d339ffdca58b3a0a5b7a8cc5080a, let me know if this is not the case.

I would like empathize that this commit is somewhat a breaking change and it requires for every user to manually update their elisp code defining `org-roam-server-light` minor mode which they copied from README the first time they started to using it.

This is why I should have properly pack this as an emacs package. This change which was needed to be done will cause some headaches to those who will `git pull` from this repo without paying the attention to changes in README.

**Comment by rnwolf** [comment]
Thanks for the update.  I hope it helps. Unfortunately I am using MS-Windows and an a Emacs/Lisp noob, so I don't know how to debug your code running on my laptop. I've prefixed  the `/tmp/...` locations  with `~` in order to get it working in my home directory.
I get a web server running, I see a file `C:\Users\rnwol\tmp\org-roam-server-light\org-roam-directory` but the web page shows no bubbles.

**Comment by AloisJanicek** [comment]
Oh, I will look into it tomorrow (today). Basically this project wasn't designed to work on systems without `/tmp` directory, but testing for OS type in python script and using Windows equivalent of `/tmp` will be easy thing to implement.

edit: I will install and configure emacs natively on Windows, I had this on my tasks list already for some time now and I will make it work

**Comment by AloisJanicek** [comment]
Sorry it took me so long, now `org-roam-server-light` should work fine on Windows. There was some issue with encoding of the files, I needed to explicitly declare `"utf8"` for textual static assets and as of https://github.com/AloisJanicek/org-roam-server-light/commit/90d227c643f0b43d141c5c8af9ea61047ae3559e the issue should be fixed.

Let me know if you run into other bugs when using this project on Windows.

**Comment by rnwolf** [comment]
Brilliant. Thanks for quick fix. 
I get the bubble graph chart and can click on nodes to get corresponding org file opened in Emacs.
Easy to install in DOOM.

1 - git clone into ~
2 - Copy elisp from readme into `config.el`
3 - Restart emacs
4 - Run `org-roam-server-light-mode`
5 - Open bowser `http://localhost:8080/`
6 - Enjoy roam notes graph.

I do have a problem with the preview for the notes content. I get 404 in iframe, but I have the same problem with the  `org-roam-server`. I did manage to get it to work once with `org-roam-server`, but then I never figured out what I did to get it working :(

Is there a setting I can use to control the display of arrows on the edges?

**Comment by rnwolf** [comment]
filePreviewHandler.py needs a change.

I get an error `Unsupported operand type(s) for +: 'WindowsPath' and 'str'`


This fixes it and now I get the iframe showing the file preview!

```
        #self.exported_file = self.export_dir + self.filename + ".html"
        self.exported_file = os.path.join(self.export_dir,self.filename+".html")
```

**Comment by AloisJanicek** [comment]
Now there should be no serious issues when running on Windows. 

Regarding the possibility of customizing graph appearance,  I am looking into updating `index.html` and the rest of the code to the latest functionality from original `org-roam-server`, so that you can customize [vis.js Network](https://visjs.github.io/vis-network/docs/network/) directly as it is possible when using [org-roam-server.el](https://github.com/org-roam/org-roam-server/blob/master/org-roam-server.el#L111)

**Comment by AloisJanicek** [comment]
As of https://github.com/AloisJanicek/org-roam-server-light/commit/be11b0902749eaee891af3638f3f3e29fab7d225 you can send custom config to vis.js Network which allows you to enable arrows and adjust a lot of things

**Comment by rnwolf** [comment]
I need to figure out how to get my Doom emacs to install the master/main version of org-roam as apposed to the latest v1.2.2 release. The latest/v1.2.2 release, still uses "from" & "to"  columns in the links table in org-roam.db.

**Comment by AloisJanicek** [comment]
Oh, sorry for this inconvenience, I didn't realize I am on master.
Until the doom updates version of `org-roam`, you need to put this into your `packages.el`
```lisp
;; .doom.d/packages.el
(unpin! org-roam)
```
and then do `doom up` (or maybe just only `doom sync` ?)

**Comment by rnwolf** [comment]
Ok. Almost working.
Line 35 of server.py need to be
        to_be_exported_file = os.path.join(org_roam_directory,requested_filename + ".org")

**Comment by AloisJanicek** [comment]
They always say "_Use the dedicated functions when manipulating file paths, you will eventually run into weird issues_". And I never listen to them.

**Comment by rnwolf** [comment]
Cool that all works like a charm. Thank you very much for your efforts.

**Comment by AloisJanicek** [comment]
I am glad that my idea and little effort could be useful for others and I thank you that you brought the Windows compatibility issues into my attention.

As of recent commit I consider this problem as solved. I will continue to improve this project so that one day the features and functionality is on a par with original `org-roam-server`. One of the first things I would like to fix is items filtering.

If you ever run into bugs while using `org-roam-server-light`, feel free to open another issue.
