### ISSUE TITLE
Links to files when in a subdirectory coming up with 404 message in browser

### ISSUE THREAD

**Issue by rnwolf** [AloisJanicek/org-roam-server-light#2]
Hi Alois

I get 404 message for nodes that live in subdirectory.
See the animated gif.

![roam-server-light-404 gif](https://user-images.githubusercontent.com/117415/97372340-56394480-18ab-11eb-9572-0700347ed3a9.gif)

![Screenshot 2020-10-27 224300](https://user-images.githubusercontent.com/117415/97369965-e2e10400-18a5-11eb-8c6c-da870cfe80b1.png)

I have the following  org-roam directory structure:

```
❯ cd OneDrive/Documents/roam
❯ tree
.
├── 20201025143623-index.org
├── 20201025143733-hello.org
├── 20201026132756-python.org
├── glossary
│   └── apple.org
└── notes
    └── glossary.org
```

When previewing apple.org or glossary.org I get 404 message in browser.

This is the data that gets sent to the http://localhost:8080/ index page.

```
{
   "nodes":[
      {
         "id":"20201025143623-index",
         "title":"index",
         "tags":null,
         "label":"index",
         "url":"org-protocol://roam-file?file=c%3A%2FUsers%2Frnwol%2FOneDrive%2FDocuments%2Froam%2F20201025143623-index.org",
         "path":"c:/Users/rnwol/OneDrive/Documents/roam/20201025143623-index.org"
      },
      {
         "id":"20201025143733-hello",
         "title":"hello",
         "tags":null,
         "label":"hello",
         "url":"org-protocol://roam-file?file=c%3A%2FUsers%2Frnwol%2FOneDrive%2FDocuments%2Froam%2F20201025143733-hello.org",
         "path":"c:/Users/rnwol/OneDrive/Documents/roam/20201025143733-hello.org"
      },
      {
         "id":"20201026132756-python",
         "title":"Python",
         "tags":null,
         "label":"Python",
         "url":"org-protocol://roam-file?file=c%3A%2FUsers%2Frnwol%2FOneDrive%2FDocuments%2Froam%2F20201026132756-python.org",
         "path":"c:/Users/rnwol/OneDrive/Documents/roam/20201026132756-python.org"
      },
      {
         "id":"glossary",
         "title":"glossary",
         "tags":"(\\""glossary\\"")",
         "label":"glossary",
         "url":"org-protocol://roam-file?file=c%3A%2FUsers%2Frnwol%2FOneDrive%2FDocuments%2Froam%2Fnotes%2Fglossary.org",
         "path":"c:/Users/rnwol/OneDrive/Documents/roam/notes/glossary.org"
      },
      {
         "id":"apple",
         "title":"Apple",
         "tags":"(\\""glossary\\"")",
         "label":"Apple",
         "url":"org-protocol://roam-file?file=c%3A%2FUsers%2Frnwol%2FOneDrive%2FDocuments%2Froam%2Fglossary%2Fapple.org",
         "path":"c:/Users/rnwol/OneDrive/Documents/roam/glossary/apple.org"
      }
   ],
   "edges":[
      {
         "from":"20201025143623-index",
         "to":"20201026132756-python",
         "arrows":null
      },
      {
         "from":"20201025143623-index",
         "to":"20201025143733-hello",
         "arrows":null
      }
   ]
}
```

I surmise that all data of nodes is being sent to the front end, but that the directories that the notes live in is being stripped out.

**Comment by AloisJanicek** [comment]
Thank you again that you let me know about the issue. I was boldly assuming that there are no nested folders inside `org-roam-directory` and that was causing problems.  I solved it by pulling the full path of the requested file from `org-roam.db` when assumption about the file being in root of `org-roam-directory` fails.

**Comment by rnwolf** [comment]
Thanks for the update.

Nested folders in roam can be used to "automatically" tag, org files in those folders. Which helps to find the information later.
See https://www.orgroam.com/manual/Tags.html

When configuring `config.el` with: `(setq org-roam-tag-sources '(prop last-directory))` we are able to use the last sub-directory as a tag to find files.

`'last-directory: Extracts the last directory relative to org-roam-directory as the tag. That is, if a file is located at relative path foo/bar/file.org, the file will have tag bar.`

After your update I can now use directories as a tagging aid, and visualize links with graph view.

**Comment by AloisJanicek** [comment]
I wasn't aware in detail of the level of usefulness and effort which was put into `org-roam` after the spring of this year. I already started to investigate those new and improved `org-roam` features and workflow possibilities and I am amazed.

**Comment by AloisJanicek** [comment]
So the issue was fixed a months ago so I am closing it.
